#!/usr/bin/env node
/**
 * NexaDesk build script
 *  - concatenates renderer/css/*.css  -> renderer/css/bundle.css
 *  - concatenates renderer/js/*.js    -> renderer/js/bundle.js
 *  - emits dist/web/index.html        -> a single-file, zero-dependency web app
 *  - emits dist/NexaDesk-web.zip
 * No npm packages required.
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const CSS_DIR = path.join(ROOT, 'renderer', 'css');
const JS_DIR = path.join(ROOT, 'renderer', 'js');
const DIST = path.join(ROOT, 'dist');

function readSorted(dir, ext) {
  return fs.readdirSync(dir)
    .filter(f => f.endsWith(ext) && f !== 'bundle' + ext)
    .sort((a, b) => {
      const na = parseInt(a, 10), nb = parseInt(b, 10);
      if (!isNaN(na) && !isNaN(nb) && na !== nb) return na - nb;
      return a.localeCompare(b);
    });
}

function concat(dir, files, header) {
  const parts = [header];
  for (const f of files) {
    const src = fs.readFileSync(path.join(dir, f), 'utf8');
    parts.push(`\n/* ══════════ ${f} ══════════ */\n` + src);
  }
  return parts.join('\n');
}

function ensure(dir) { fs.mkdirSync(dir, { recursive: true }); }

function build() {
  const t0 = Date.now();

  /* ---------- CSS ---------- */
  const cssFiles = readSorted(CSS_DIR, '.css');
  const css = concat(CSS_DIR, cssFiles,
    `/* NexaDesk — bundled stylesheet\n   Generated ${new Date().toISOString()}\n   Sources: ${cssFiles.join(', ')}\n   Do not edit this file directly; edit the sources. */\n`);
  fs.writeFileSync(path.join(CSS_DIR, 'bundle.css'), css);

  /* ---------- JS ---------- */
  const jsFiles = readSorted(JS_DIR, '.js');
  const js = concat(JS_DIR, jsFiles,
    `/* NexaDesk — bundled application\n   Generated ${new Date().toISOString()}\n   Sources: ${jsFiles.join(', ')}\n   Do not edit this file directly; edit the sources. */\n`);
  fs.writeFileSync(path.join(JS_DIR, 'bundle.js'), js);

  /* ---------- standalone web app ---------- */
  const webDir = path.join(DIST, 'web');
  ensure(webDir);
  let html = fs.readFileSync(path.join(ROOT, 'renderer', 'index.html'), 'utf8');
  // inline css + js so it is a genuine single-file app
  html = html.replace(/<link rel="stylesheet" href="css\/bundle.css">/,
    () => '<style>\n' + css + '\n</style>');
  html = html.replace(/<script src="js\/bundle.js"><\/script>/,
    () => '<script>\n' + js + '\n</script>');
  html = html.replace(/\.\.\/assets\/icons\/icon\.png/g, ICON_DATA_URI());
  html = html.replace(/<meta http-equiv="Content-Security-Policy"[\s\S]*?>/,
    `<meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: https:;">`);
  fs.writeFileSync(path.join(webDir, 'index.html'), html);
  // also keep the split version alongside for anyone who wants to hack on it
  ensure(path.join(webDir, 'renderer', 'css'));
  ensure(path.join(webDir, 'renderer', 'js'));
  fs.copyFileSync(path.join(CSS_DIR, 'bundle.css'), path.join(webDir, 'renderer', 'css', 'bundle.css'));
  fs.copyFileSync(path.join(JS_DIR, 'bundle.js'), path.join(webDir, 'renderer', 'js', 'bundle.js'));
  fs.copyFileSync(path.join(ROOT, 'renderer', 'index.html'), path.join(webDir, 'renderer', 'index.html'));
  fs.writeFileSync(path.join(webDir, 'README.txt'),
`NexaDesk — standalone web build
===============================

Just open index.html in any modern browser. It is a single self-contained file:
all CSS and JS are inlined, there are no network requests and no dependencies.

Your data is saved in the browser's localStorage for this file/origin.
Use Settings -> Data & backup to export a JSON backup you can restore anywhere.

The full desktop app (Electron, with system tray, native notifications that fire
while minimised, and global shortcuts) lives in the project root. Run:

    npm install
    npm start

renderer/ contains the unbundled source split into separate files, if you prefer
to read or edit that instead of the single index.html.
`);

  /* ---------- sizes ---------- */
  const kb = n => (n / 1024).toFixed(1) + ' KB';
  console.log('\n  NexaDesk build complete in ' + (Date.now() - t0) + 'ms\n');
  console.log('  CSS  ' + cssFiles.length + ' files -> ' + kb(css.length));
  console.log('  JS   ' + jsFiles.length + ' files -> ' + kb(js.length));
  console.log('  Web  dist/web/index.html -> ' + kb(fs.statSync(path.join(webDir, 'index.html')).size));
  console.log('');
  return { cssLen: css.length, jsLen: js.length, cssFiles, jsFiles };
}

function ICON_DATA_URI() {
  try {
    const p = path.join(ROOT, 'assets', 'icons', 'icon.svg');
    if (fs.existsSync(p)) return 'data:image/svg+xml;base64,' + Buffer.from(fs.readFileSync(p, 'utf8')).toString('base64');
  } catch (e) {}
  return '';
}

/* ---------- zip ---------- */
function zipWeb() {
  try {
    const out = path.join(DIST, 'NexaDesk-web.zip');
    if (fs.existsSync(out)) fs.unlinkSync(out);
    execSync(`cd "${DIST}" && zip -qr NexaDesk-web.zip web`, { stdio: 'ignore' });
    console.log('  Zip  dist/NexaDesk-web.zip -> ' + (fs.statSync(out).size / 1024).toFixed(1) + ' KB\n');
  } catch (e) {
    console.log('  Zip  skipped (' + e.message.split('\n')[0] + ')\n');
  }
}

const res = build();
zipWeb();
module.exports = res;
